micronaut:
  application:
    name: mnStockBroker
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  openapi:
    views:
      spec: "swagger-ui.enabled=true,swagger-ui.theme=flattop"


jackson:
#  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  generator:
    writeNumbersAsStrings: false
    writeBigDecimalsAsPlain: false
  deserialization:
    failOnUnkownProperties: false