micronaut:
  application:
    name: mnStockBroker
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  openapi:
    views:
      spec: "swagger-ui.enabled=true,swagger-ui.theme=flattop"
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretToALongSecureString
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://localhost:5432/stockbroker`}
      username: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:}
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://localhost:5432/stockbroker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - "com.practice"
    properties:
      hibernate:
        show_sql: false




jackson:
#  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  generator:
    writeNumbersAsStrings: false
    writeBigDecimalsAsPlain: false
  deserialization:
    failOnUnkownProperties: false